# Generated by Django 4.2.28 on 2026-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('message_body', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], default='sent', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
