# Generated by Django 4.2.28 on 2026-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USSDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('ussd_code', models.CharField(blank=True, max_length=200)),
                ('telecom', models.CharField(max_length=10)),
                ('intent', models.CharField(max_length=100)),
                ('raw_response', models.TextField(blank=True)),
                ('parsed_response', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
