# Generated by Django 4.2.28 on 2026-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('audio_duration_ms', models.IntegerField(default=0)),
                ('detected_language', models.CharField(default='eng', max_length=3)),
                ('transcribed_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
