# Generated by Django 4.2.28 on 2026-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('input_text', models.TextField()),
                ('detected_intent', models.CharField(max_length=100)),
                ('entities', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
