# Generated by Django 4.2.28 on 2026-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('turn_number', models.IntegerField(default=1)),
                ('user_input_text', models.TextField(blank=True)),
                ('system_response_text', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['session_id', 'turn_number'],
            },
        ),
    ]
