# Generated by Django 4.2.28 on 2026-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('send', 'Send Money'), ('receive', 'Receive Money'), ('balance', 'Balance Check'), ('airtime', 'Buy Airtime'), ('data', 'Buy Data'), ('loan', 'Loan')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('telecom', models.CharField(choices=[('MTN', 'MTN Uganda'), ('AIRTEL', 'Airtel Uganda')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('telecom_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
